In [323]:
import numpy as np
import pandas as pd
from scipy import optimize

In [324]:
nr_mults = np.random.randint(low=3, high=5)
dims_per_mult = np.random.randint(low=2, high=3, size=nr_mults)

In [325]:
muls=list()
dims=list()
for mul in range(0,nr_mults):
    for dim in range(0,dims_per_mult[mul]):
        muls.append('mul_'+str(mul))
        dims.append('dim_'+str(dim))
df = pd.DataFrame(data = {'muls': muls,
                         'dims': dims}
                  , columns=['muls','dims'])
#df = df[['muls','dims']]
df['code'] = ['w['+str(i)+']' for i in range(0,len(df))]

uniq_mults =np.unique(df.muls)

df_fin = df[df.muls==uniq_mults[0]][['code']].rename(columns={'code':'code_'+uniq_mults[0]})
df_fin.loc[:, 'dummy_var']=1;
for mul in uniq_mults[1:]:
    df_temp=df[df.muls==mul][['code']].rename(columns={'code':'code_'+mul})
    df_temp.loc[:, 'dummy_var']=1
    df_fin = df_fin.merge(df_temp,on = 'dummy_var')
df_fin = df_fin.drop('dummy_var',axis=1)
df_fin.loc[:, 'prod_format'] = df_fin.apply(lambda row: '*'.join(map(str, row.values)), axis=1)
k_values_str = np.random.uniform(0,2,size=len(df_fin))+2
df_fin.loc[:, 'k_values'] = k_values_str

In [326]:
expression = '' 
for i in range(0,len(df_fin)):
    expression+= 'np.abs(('+df_fin.loc[i].prod_format+'-'+str(df_fin.loc[i].k_values)+')/'+str(df_fin.loc[i].k_values)+')+'
expression = expression[:-1]
#expression

In [327]:
obj_fun_str =  """def obj_fun(w):
    return {}""".format(expression)

In [328]:
exec(obj_fun_str)

In [329]:
bnds = ((0.000001, 10000),)*len(df)
solution = optimize.minimize(obj_fun,np.ones(len(df)), bounds=bnds)
w = solution.x
#solution

In [330]:
df.loc[:, 'result'] = w
df_fin.loc[:, 'resulted_values'] = df_fin['prod_format'].apply(lambda row: eval(row))

In [331]:
df

    muls   dims  code    result
0  mul_0  dim_0  w[0]  1.348656
1  mul_0  dim_1  w[1]  1.173355
2  mul_1  dim_0  w[2]  1.321262
3  mul_1  dim_1  w[3]  1.276116
4  mul_2  dim_0  w[4]  1.233698
5  mul_2  dim_1  w[5]  1.380404
6  mul_3  dim_0  w[6]  1.289806
7  mul_3  dim_1  w[7]  1.271394

In [332]:
df_fin

,code_mul_0,code_mul_1,code_mul_2,code_mul_3,prod_format,k_values,resulted_values
0,w[0],w[2],w[4],w[6],w[0]*w[2]*w[4]*w[6],2.835892,2.835458
1,w[0],w[2],w[4],w[7],w[0]*w[2]*w[4]*w[7],3.954346,2.794983
2,w[0],w[2],w[5],w[6],w[0]*w[2]*w[5]*w[6],2.491360,3.172637
3,w[0],w[2],w[5],w[7],w[0]*w[2]*w[5]*w[7],2.737371,3.127349
4,w[0],w[3],w[4],w[6],w[0]*w[3]*w[4]*w[6],2.738575,2.738575
5,w[0],w[3],w[4],w[7],w[0]*w[3]*w[4]*w[7],2.682526,2.699483
6,w[0],w[3],w[5],w[6],w[0]*w[3]*w[5]*w[6],3.181539,3.064233
7,w[0],w[3],w[5],w[7],w[0]*w[3]*w[5]*w[7],3.297490,3.020492
8,w[1],w[2],w[4],w[6],w[1]*w[2]*w[4]*w[6],3.764815,2.466900
9,w[1],w[2],w[4],w[7],w[1]*w[2]*w[4]*w[7],2.154565,2.431686
10,w[1],w[2],w[5],w[6],w[1]*w[2]*w[5]*w[6],2.764212,2.760252
11,w[1],w[2],w[5],w[7],w[1]*w[2]*w[5]*w[7],3.653160,2.720850
12,w[1],w[3],w[4],w[6],w[1]*w[3]*w[4]*w[6],2.382597,2.382609
13,w[1],w[3],w[4],w[7],w[1]*w[3]*w[4]*w[7],2.551477,2.348599
14,w[1],w[3],w[5],w[6],w[1]*w[3]*w[5]*w[6],2.627796,2.665938
15,w[1],w[3],w[5],w[7],w[1]*w[3]*w[5]*w[7],2.627882,2.627883